KingaMiko/wallet-application

Frontend/src/App.jsx, Frontend/src/components/LoginForm/LoginForm.jsx, Frontend/src/components/RegistrationForm/RegistrationForm.jsx
Dodałam Linki w formularzach do strony z logowaniem/rejestracją
Plus wstępnie Suspense w App
=> add router Link to auth pages in forms

Frontend/src/sass/partials/_buttons.scss
added btn.scss:
- logIn
- register
- statistics
- delete
=> added btn.scss: logIn/register/statistics/delete

Backend/package.json, Backend/schemas/loginUser.schema.js, Backend/schemas/registerUser.schema.js
Nie działał mi mi backend bo node musi mieć rozszerzenia plików w scieżkach importów, i za importowałem password pattern do login schema.
=> Cham zpod lasu/porzadki

Backend/controllers/categories/getCategory.js, Backend/controllers/statistics/getStatistics.js, Backend/controllers/transactions/addTransaction.js, Backend/controllers/transactions/getTransactions.js, Backend/controllers/users/getUser.js, Backend/plugins/swaggerPlugin.js, Backend/routes.js
przeniosłem specyfikacje do dokumentacji z pliku routes do kontrolerów
=> move api doc specs to controllers

Backend/controllers/auth/authSignup.js, Backend/controllers/auth/authSingin.js, Backend/controllers/curriencies/addCurrency.js, Backend/controllers/curriencies/getCurrencies.js, Backend/controllers/curriencies/getCurrency.js, Backend/controllers/curriencies/updateCurrencies.js, Backend/controllers/index.js, Backend/controllers/users/verifyUser.js, Backend/models/currency.js, Backend/models/user.js, Backend/package-lock.json, Backend/package.json, Backend/routes.js, Backend/server.js
Stworzyłem kontrolery do aktualizacji oraz pobierania kursów walut, oraz dodałem odpalanie aktualizacji kursów walut na co minute, można zwiększyć potem na raz dziennie o połnocy jak skończe testy
=> Grzegorz j/currencies

Frontend/src/components/Button/Button.jsx
Dodałam propsa className do modyfikacji Button przez innych członków zespołu
=> add className prop for Button component

Backend/controllers/auth/authLogout.js, Backend/controllers/auth/authRefresh.js, Backend/controllers/auth/authSignup.js, Backend/controllers/auth/authSingin.js, Backend/controllers/index.js, Backend/controllers/users/getUser.js, Backend/controllers/users/verifyUser.js, Backend/plugins/authPlugin.js, Backend/routes.js, Backend/schemas/swagger.schema.js
Stworzyłem mechanizm odświeżania sesji użytkownika za pomocą ciastek. W redux session trzeba będzie wywoływać żądanie /api/auth/refresh (żeby dostać nowe tokeny) kiedy w odpowiedzi żądania żadania /api/users/current (lub jakiekolwiek innego zablokowanego przez mw auth) przyjdzie kod 401 i komunikat "Access expired".
Jak zmergujesz to to zajme się blacklistingiem
=> Grzegorz j/refresh user

Backend/app.js, Backend/controllers/auth/authRefresh.js, Backend/controllers/auth/authSingin.js, Backend/models/session.js, Backend/package-lock.json, Backend/package.json, Backend/plugins/authPlugin.js
Dodałem mechanizm wykrywania użycia kradzionych/przechwyconych ciastek w celu podszycia się pod użytkownika za pomocą starego ale nadal aktualnego refresh tokena. Czyszczenie bazy danych z starych sesji które już nie są aktualne. Oprócz tego trochę refactoringu w celu nie duplikowania kodu.
=> Grzegorz j/blacklisting

Frontend/src/.env, Frontend/src/App.jsx, Frontend/src/components/PrivateRoute/PrivateRoute.jsx, Frontend/src/components/RestrictedRoute/RestrictedRoute.jsx, Frontend/src/hooks/useAuth.js, Frontend/src/redux/session/operations.js, Frontend/src/redux/session/sessionSlice.js
Działa już (przynajmniej u mnie ;) ) utrzymywanie podstrony Home lub Statistics po odświeżeniu całej strony. 
To jeszcze nie koniec bo po wygaśnięciu tokena (jeśli nikt nic nie zmieniał to po 10 min) i tak trzeba będzie się zalogować. 
Jak połączysz to z main to się tym zajmę.
=> Grzegorz j/auth frontend

Frontend/src/components/Header/Categories.jsx, Frontend/src/components/Header/Categories.module.scss, Frontend/src/components/Header/Header.jsx, Frontend/src/components/Header/Header.module.scss, Frontend/src/pages/Home/Home.module.scss, Frontend/src/redux/finance/operations.js
Dodawanie i usuwanie kategorii
=> Categoriess

Backend/controllers/statistics/getStatistics.js, Backend/routes.js
poprawiłem swaggera i zmieniłem route getstatistics na post
=> route change and swagger fix 

Frontend/.env.example, Frontend/src/pages/RedirectPage/RedirectPage.jsx, Frontend/src/utils/api.js
Dodany env example na frontend
=> update redirect path

Frontend/src/components/Balance/Balance.module.scss, Frontend/src/components/Button/Button.module.scss, Frontend/src/components/CurrencyTable/CurrencyTable.module.scss
Media query added to some of the components: 
- Balance
- Button
- CurrencyTable
=> mq added to Balance,Button,CurrencyTable

Backend/controllers/categories/getCategories.js, Frontend/src/App.jsx, Frontend/src/components/Header/Categories.jsx, Frontend/src/components/TransactionsManager/ModalAddTransaction/ModalAddTransaction.jsx, Frontend/src/components/TransactionsManager/ModalEditTransaction/ModalEditTransaction.jsx
Te commity od Sylwi są bo mergowałem jej zmiany z finance slice dla testów i szukania błędów, sprawdź tylko te moje.
=> Grzegorz categories

Backend/controllers/transactions/getTransactions.js, Backend/helpers/transactionHelper.js
Reverts KingaMiko/wallet-application#177
=> Revert "Pagination"

Backend/controllers/transactions/getTransactions.js
Reverts KingaMiko/wallet-application#195
=> Revert "fix december"

Backend/controllers/transactions/getTransactions.js
Reverts KingaMiko/wallet-application#194
=> Revert "fix month index"

Backend/controllers/transactions/getTransactions.js
Reverts KingaMiko/wallet-application#193
=> Revert "getTransaction gottenMonth change"

Backend/helpers/transactionHelper.js, Frontend/src/components/TransactionsManager/FilterTransaction/FilterTransaction.jsx
Reverts KingaMiko/wallet-application#192
=> Revert "findTransaction fix"

Backend/controllers/transactions/getTransactions.js
Reverts KingaMiko/wallet-application#191
=> Revert "backend fix"

Backend/controllers/transactions/getTransactions.js
Reverts KingaMiko/wallet-application#190
=> Revert "fix month"

Backend/controllers/transactions/getTransactions.js, Frontend/src/components/TransactionsManager/TransactionManager.jsx
Reverts KingaMiko/wallet-application#189
=> Revert "getTransaction on backend fix"

Backend/helpers/transactionHelper.js, Frontend/src/components/TransactionsManager/TransactionManager.jsx
Reverts KingaMiko/wallet-application#204
=> Revert "Paginationbymonth"

Frontend/public/404.html
Reverts KingaMiko/wallet-application#212
=> Revert "404.html change"
